apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yml
- namespace.yml
- route.yml
- sa.yml
- service.yml
namespace: rafflequiz

images:
- name: localhost/rafflequiz
  newName: quay.io/rhn_support_milang/rafflequiz
  newTag: v1.0.0
