name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
     inputs:
          event_id:
            description: 'Unique Event ID'
            required: true
            type: string
          context_dir:
            description: 'Context Directory'
            required: false
            type: string

concurrency:
    group: ${{ github.workflow }}-${{ github.event.inputs.event_id }}
    cancel-in-progress: false 
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag quay.io/rhn_support_milang/rafflequiz:$(date +%s)
